### ISSUE TITLE
ddp driver in C++

### ISSUE THREAD

**Issue by dhthong92** [jszaszvari/rocketchat-ddp-listener#1]
Hi jszaszvari,
I think it's better to move [my issue](https://github.com/RocketChat/Rocket.Chat/issues/7272) to here.
I've already tried your scripts successfully. But my client is written in C++, so I wonder is there any driver at client support DDP protocol in C++? I've searched around but could not find any suitable as ddpjs you used. So if it does not support in C++, I would have to write a temporary server in NodeJs to manage and transfer the subscription response messages from RC server to my client and I guess it's not efficient.
Thanks for your help again!

**Comment by JSzaszvari** [comment]
https://github.com/alexhancock/ddp-cpp
