### ISSUE TITLE
Then? How can we use it?

### ISSUE THREAD

**Issue by Naguchennai** [jszaszvari/rocketchat-ddp-listener#2]
Edit the 'listen_to_room.js' script and fill in the 'authToken' and 'subscription' variables
ok finished .. 

then what? 

how can i get real time?

https://rocket.chat/docs/developer-guides/rest-api/channels/history

this come in real time in curl output? lol

**Comment by JSzaszvari** [comment]
Run that file.

After editing it, run it with node like

```
node listen_to_room.js
```

**Comment by JulioSantanaR** [comment]
@JSzaszvari is possible to use this Node native code in browsers???
encapsulating the packages, for example in a webpack (i'm using net core) ??
